### ISSUE TITLE
Scoring error

### ISSUE THREAD

**Issue by rzkxaa** [YU-java-211/Year-Up-Java-Winter-2021-Final-Project-Card-Game#16]
Adding up the points for the winner doesn't math up.

**Comment by azdela** [comment]
Fix issue by adding Private int field

**Comment by azdela** [comment]
New bug where the output of "Player #" starts at 0 rather than one. Rather than saying "Player 1" output shows "Player 0"

**Comment by azdela** [comment]
Fix bug by adding "+ 1" to the I variable in the for loop to start at Player 1 rather than 0

**Comment by rzkxaa** [comment]
Solved the issues.
